package models;

import java.util.Random; 

public class logiccarpark extends abstractmodel {
    private static int numberOfFloors;
    private static int numberOfRows;
    private static int numberOfPlaces;
    private static CarQueue entranceCarQueue;
    private static CarQueue paymentCarQueue;
    private static CarQueue membersCarQueue;
    private static CarQueue exitCarQueue;
    private car[][][] cars;
    private int stayMinutes;
    private double revenue;
    private double totalRevenue;
    private double memberRevenue;
    
    
    // amount of pass holders allowed in the car park
    int amountOfPassHolders;
    // amount of reservations in the car park
    int amountOfReservations;
    
    private int day = 0;
    private int hour = 0;
    private int minute = 0;

    int weekDayArrivals= 50; // average number of arriving cars per hour
    int weekendArrivals = 70; // average number of arriving cars per hour

    int enterSpeed;
    int paymentSpeed;
    int exitSpeed; 
    
    // Keeping track of statistics
    int numberOfEnteringCars; // how many cars are in entranceCarQueue
    int numberOfPayingCars; // how many cars are in paymentCarQueue
    int numberOfExitingCars; // how many cars are in exitCarQueue
    int numberOfMembersExiting; // how many cars are in the membersCarQueue
    int totalCars; // amount of no member cars in car park 
    int totalPassHolders; // amount of members in car park
    int totalReservations; // amount of cars with reservation in car park
    int total; // amount of all cars in car park
    
    //DayView Info
    String currentDay; // Keeps track what day it currently is in a String

    /**
     * Constructor of the CarPark. It initializes the fields and creates the
     * three dimensional array to represent the parking spots in the car park.
     *
     * @param numberOfFloors The number of floors of the car park
     * @param numberOfRows   The number of rows per floor of the car park
     * @param numberOfPlaces The number of parking spots per row of the car park
     */
    public logiccarpark(int numberOfFloors, int numberOfRows, int numberOfPlaces) {
        this.numberOfFloors = numberOfFloors;
        this.numberOfRows = numberOfRows;
        this.numberOfPlaces = numberOfPlaces;

        entranceCarQueue = new CarQueue();
        paymentCarQueue = new CarQueue();
        membersCarQueue = new CarQueue();
        exitCarQueue = new CarQueue();
        
        enterSpeed = 10; // number of cars that can enter per minute
        paymentSpeed = 7; // number of cars that can pay per minute
        exitSpeed = 7; // number of cars that can leave per minute
        
        // amount of cars that have membership at the car park
        amountOfPassHolders = 150;
        // amount of cars that have a reservation at the car park
        amountOfReservations = getRandInt(110, 90);
        
        // counting different cars to be able to visualize this data
        numberOfEnteringCars = 0;
        numberOfPayingCars = 0;
        numberOfExitingCars = 0;
        numberOfMembersExiting = 0;
        totalCars = 0;
        totalPassHolders = 0;
        totalReservations = 0;
        
        revenue = 0.0;
        totalRevenue = 0.00;
        memberRevenue = (150 * 50); 

        cars = new car[numberOfFloors][numberOfRows][numberOfPlaces];
        
        currentDay = "Zondag";
    }
    
    //een random nummer voor een nieuwe week aanmaken
    /**
     * This method creates a random number, where min and max are the boundries between which the
     * random number should lie.
     * @param min
     * @param max
     * @return returns a random number between the min and max value 
     */
    public int getRandInt(int max, int min){
    	
    	Random rand;
    	rand = new Random();
    	
    	int randNum = rand.nextInt(max - min) + min; 
    	
    	return randNum;
    }
    
    /**
     * @return roundedTwoDecimals Returns the total amount of revenue generated by normalCustomers rounded by 2 decimals.
     */
    public String getRevenueNormal(){
    	totalRevenue = totalRevenue + revenue;
    	String roundedTwoDecimals = String.format( "%.2f", totalRevenue);
    	return roundedTwoDecimals; 
    }
    
    /**
     * @return roundedTwoDecimals Returns the total amount of revenue generated by members rounded by 2 decimals
     */
    public String getRevenueMembers(){
    	String roundedTwoDecimals = String.format( "%.2f", memberRevenue);
    	return roundedTwoDecimals;
    }
    
    /**
     * @return roundedTwoDecimals Returns the total amount of all revenue rounded by two decimals
     */
    public String getRevenueTotal(){
    	String roundedTwoDecimals = String.format( "%.2f", (memberRevenue + totalRevenue));
    	return roundedTwoDecimals;
    }
    
    /**
     * @return String	Returns a string of the time
     */
    public String getTime(){
    	return("day(s): " + day + "   " + "hour(s): " + hour + "   " + "minute(s): " + minute);
    }

    /**
     * Get number of floors of the car park.
     *
     * @return numberOfFloors Number of floors of the car park
     */
    public int getNumberOfFloors() {
        return numberOfFloors;
    }

    /**
     * Get number of rows of the car park.
     *
     * @return numberOfRows Number of rows of the car park
     */
    public int getNumberOfRows() {
        return numberOfRows;
    }

    /**
     * Get number of parking spots in the car park.
     *
     * @return numberOfPlaces Number of parking spots in the car park
     */
    public int getNumberOfPlaces() {
        return numberOfPlaces;
    }

    /**
     * Get the three dimensional array that represents the car park.
     *
     * @return cars Return the array cars
     */
    public car[][][] getCars() {
        return cars;
    }

    /**
     * Get queue of all the cars are entering the car park.
     *
     * @return cars Return the queue with all cars entering
     */
    public CarQueue getEntranceCarQueue() {
        return entranceCarQueue;
    }

    /**
     * Get queue of all the cars that need to pay at the car park.
     *
     * @return cars Return the queue with all cars that need to pay
     */
    public CarQueue getPaymentCarQueue() {
        return paymentCarQueue;
    }

    /**
     * Get queue of all the cars are exiting the car park.
     *
     * @return cars Return the queue with all cars exiting
     */
    public CarQueue getExitCarQueue() {
        return exitCarQueue;
    }
    
    /**
     * Change entering speed.
     * 
     * @param newSpeed The speed the user wants to change the entering speed to.
     */
    public void setEnterSpeed(int newSpeed) {
    	enterSpeed = newSpeed;
    }
    
    /**
     * Change payment speed.
     * 
     * @param newSpeed The speed the user wants to change the payment speed to.
     */
    public void setPaySpeed(int newSpeed) {
    	paymentSpeed = newSpeed;
    }
    
    /**
     * Change exiting speed.
     * 
     * @param newSpeed The speed the user wants to change the exiting speed to.
     */
    public void setExitSpeed(int newSpeed) {
    	exitSpeed = newSpeed;
    }
    
    /**
     * @return enterSpeed The speed with which cars currently are entering per minute.
     */
	public int getEnterSpeed() {
		return enterSpeed;
	}
	
    /**
     * @return paymentSpeed The speed with which car owners currently are paying per minute.
     */
	public int getPaySpeed() {
		return paymentSpeed;
	}
	
    /**
     * @return exitSpeed The speed with which cars currently are exiting per minute.
     */
	public int getExitSpeed(){
		return exitSpeed;
	}

    /**
     * Executes one simulation step, it advances the time by one minute.
     */
    public void tick() {
        // Advance the time by one minute.
        minute++;
        if (minute > 59) {
            minute -= 60;
            hour++;
        }
        if (hour > 23) {
            hour -= 24;
            day++;
        }
        if (day > 6) {
            day -= 7;
        }
        
        switch(day)
        {
           case 0:
              currentDay = "Maandag"; 
              break;
           case 1:
        	   currentDay = "Dinsdag";
        	   break;
           case 2:
              currentDay = "Woensdag";
              break;
           case 3:
              currentDay = "Donderdag";
              break;
           case 4:
        	  currentDay = "Vrijdag"; 
              break;
           case 5:
         	  currentDay = "Zaterdag"; 
              break;
           case 6:
          	  currentDay = "Zondag"; 
              break;
        }

        Random random = new Random();

        // Get the average number of cars that arrive per hour.
        int averageNumberOfCarsPerHour = day < 5
                ? weekDayArrivals
                : weekendArrivals;

        // Calculate the number of cars of people who are not members that arrive this minute.
        double standardDeviation = averageNumberOfCarsPerHour * 0.1;
        double numberOfCarsPerHour = averageNumberOfCarsPerHour + random.nextGaussian() * standardDeviation;
        int numberOfCarsPerMinute = (int)Math.round(numberOfCarsPerHour / 60);
    
        double numberOfReservationsPerHour = (amountOfReservations / 4) + random.nextGaussian() * standardDeviation;
        int numberOfReservationsPerMinute = (int)Math.round(numberOfReservationsPerHour / 60);
   
        // Calculates the number of members that arrive each minute.
        double numberOfMembersPerHour = (amountOfPassHolders / 6) + random.nextGaussian() * standardDeviation;
        int numberOfMembersPerMinute = (int)Math.round(numberOfMembersPerHour / 60);
        int numberTotalCarsPerMinute = numberOfCarsPerMinute + numberOfMembersPerMinute;

        // Add the cars of people who are not members to the back of the entrance queue.
        for (int j = 0; j < numberTotalCarsPerMinute; j++) { 
            for (int i = 0; i < numberOfCarsPerMinute; i++) {
                car car = new AdHocCar();
                numberOfEnteringCars++;
                totalCars++;
                entranceCarQueue.addCar(car);
            }
            
          //Reservatie code
            //will be added to the membersExitQueue
            for (int i = 0; i < numberOfReservationsPerMinute ; i++) {
                car car = new reservation();
                numberOfEnteringCars++;
                totalReservations++;
                entranceCarQueue.addCar(car);
            }

            // Add the cars of members to the back of the entrance queue.
            for (int i = 0; i < numberOfMembersPerMinute ; i++) {
                car car = new passholder();
                numberOfEnteringCars++;
                totalPassHolders++;
                entranceCarQueue.addCar(car);
            }

            super.notifyViews();
        }

        // Remove car from the front of the queue and assign to a parking space.
        for (int i = 0; i < enterSpeed; i++) {
        
            car car = entranceCarQueue.removeCar();

            if (car == null) {
                break;
            } else {
            	numberOfEnteringCars--;
            }
            // Find a space for this car.
            location freeLocation = this.getFirstFreeLocation();
            if (freeLocation != null) {
                this.setCarAt(freeLocation, car);
             
                if(car instanceof reservation){
                	car.setMinutesLeft(car.getStayTime());
                	 
                } else if(car instanceof AdHocCar || car instanceof passholder) {
                		car.setMinutesLeft(car.getStayTime());
                
              }
            }
            super.notifyViews();
        }

        this.tickCars();

        // Add leaving cars to the exit queue.
        while (true) {
            car car = this.getFirstLeavingCar();
            if (car == null) {
                break;
            }

            //if a car isn't a member it goes to the payment queue else it goes to the members queue,
            // members pay monthly so they don't need to pay.
            if(car instanceof AdHocCar){
            	numberOfPayingCars++;
            	paymentCarQueue.addCar(car);
            	break;
            	
            	
            } else if(car instanceof passholder || car instanceof reservation) { 
                numberOfMembersExiting++;
            	membersCarQueue.addCar(car);
                this.removeCarAt(car.getLocation());
                if (car instanceof passholder) {
                	totalPassHolders--;
                } else {
                	totalReservations--;
                }
                break;
            }
            

            super.notifyViews();
        }

         // Let cars pay.
        for (int i = 0; i < paymentSpeed; i++) {
            car car = paymentCarQueue.removeCar();
            if (car == null) {
                break;
            } else {
                numberOfPayingCars--;
                revenue = car.getStayTime() * 0.03; 
            }

            this.removeCarAt(car.getLocation());
            exitCarQueue.addCar(car);
            numberOfExitingCars++;
            totalCars--;
            super.notifyViews(); 
        }
        

        // Let non members leave.
        for (int i = 0; i < exitSpeed; i++) {
            car car = exitCarQueue.removeCar();
            if (car == null) {
                break;
            } else {
                numberOfExitingCars--;	
            }
            super.notifyViews();
            // Bye!
        }

        // Let members leave.
        for (int i = 0; i < exitSpeed; i++) {
            car car = membersCarQueue.removeCar();
            if (car == null) {
                break;
            } else {
            	numberOfMembersExiting--;
            }
            super.notifyViews(); 
            // Bye!
        }
        
        total = totalCars + totalPassHolders + totalReservations;
        // Update the car park view.
        super.notifyViews();
    }

    /**
     * For every car call the tick method by looping through the car park.
     */
    private void tickCars() {
        for (int floor = 0; floor < getNumberOfFloors(); floor++) {
            for (int row = 0; row < getNumberOfRows(); row++) {
                for (int place = 0; place < getNumberOfPlaces(); place++) {
                    location location = new location(floor, row, place);
                    car car = this.getCarAt(location);
                    if (car != null) {
                        car.tick();
                    }
                }
            }
        }
    }

    /**
     * Get a car from a specific location in the car park.
     *
     * @param location A Location object which stores where the car is parked.
     * @return car The car that is parked at the given location.
     */
    public car getCarAt(location location) {
        if (!locationIsValid(location)) {
            return null;
        }
        return cars[location.getFloor()][location.getRow()][location.getPlace()];
    }

    /**
     * Put a car in a certain parking spot, a certain Location in the car park.
     *
     * @param location Location object where the car should be parked
     * @param car The car that needs to be parked
     * @return boolean Return true if the car is successfully parked, if not return false
     */
    public boolean setCarAt(location location, car car) {
        if (!locationIsValid(location)) {
            return false;
        }
        car oldCar = getCarAt(location);
        if (oldCar == null) {
            cars[location.getFloor()][location.getRow()][location.getPlace()] = car;
            car.setLocation(location);
            return true;
        }
        return false;
    }
    
    /**
     * Check if a specific location is empty in the car park.
     *
     * @param location Location to check
     * @return boolean Return true if location is empty, if not return
     */
    private boolean locationIsValid(location location) {
        int floor = location.getFloor();
        int row = location.getRow();
        int place = location.getPlace();
        if (floor < 0 || floor >= numberOfFloors || row < 0 || row > numberOfRows || place < 0 || place > numberOfPlaces) {
            return false;
        }
        return true;
    }

    /**
     * Gets the first free parking spot that is empty in the car park.
     *
     * @return location | null If empty location is found return location, if not return null 
     */
    public location getFirstFreeLocation() {
        for (int floor = 0; floor < getNumberOfFloors(); floor++) {
            for (int row = 0; row < getNumberOfRows(); row++) {
                for (int place = 0; place < getNumberOfPlaces(); place++) {
                    location location = new location(floor, row, place);
                    if (getCarAt(location) == null) {
                        return location;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Get the first leaving car in the car park.
     *
     * @return car | null | If a leaving car is found return this car, if not return null
     */
    public car getFirstLeavingCar() {
        for (int floor = 0; floor < getNumberOfFloors(); floor++) {
            for (int row = 0; row < getNumberOfRows(); row++) {
                for (int place = 0; place < getNumberOfPlaces(); place++) {
                    location location = new location(floor, row, place);
                    car car = getCarAt(location);
                    if (car != null && car.getMinutesLeft() <= 0) {
                        return car;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Remove a car at a specific location in the car park.
     *
     * @param location Location of the car that needs to be removed
     * @return car | null | If the location is not valid or there is no car at the 
     *                      specified location return null, else return the car
     */
    public car removeCarAt(location location) {
        if (!locationIsValid(location)) {
            return null;
        }
        car car = getCarAt(location);
        if (car == null) {
            return null;
        }
        cars[location.getFloor()][location.getRow()][location.getPlace()] = null;
        car.setLocation(null);
        return car;
    }
    
    /**
     * Set steps in the simulator
     *
     * @param steps Amount of steps we should do
     */
    public void setSteps(int steps) {
        for(int i = 0; i < steps; i++) {
            tick();
        }
    }
    
    /**
     * @return numberOfEnteringCars
     */
    public int getNumberOfEntering() {
        return numberOfEnteringCars;
    }

    /**
     * @return numberOfPayingCars
     */
    public int getNumberOfPaying() {
        return numberOfPayingCars;
    }

    /**
     * @return numberOfExitingCars
     */
    public int getNumberOfExiting() {
        return numberOfExitingCars;
    }
    
    /**
     * @return numberOfExitingCars
     */
    public int getNumberOfExitingMembers() {
        return numberOfMembersExiting;
    }
    
    /**
     * @return totalCars Return total number of no member cars in car park
     */
    public int getTotalCars() {
        return totalCars;
    }

    /**
     * @return totalCars Return total number of members in car park
     */
    public int getTotalPassHolders() {
        return totalPassHolders;
    }
    
    /**
     * @return totalCars Return total number of members in car park
     */
    public int getTotalReservations() {
        return totalReservations;
    }
    
    /**
     * @return currentDay The day in a String form
     */
    public String getCurrentDay(){
    	return currentDay;
    }
    
    /**
     * @param newDay The new day in a String format
     */
    public void setCurrentDay(String newDay){
    	currentDay = newDay;
    }
    
    /**
     * @return amountOfPassHolders Amount of pass holders allowed in the car park
     */
    public int getNumberOfPassHolders(){
    	return amountOfPassHolders;
    }
    
    /**
     * Change the amount of pass holders allowed in the car park.
     * @param newNumber The new amount to set
     */
    public void setNumberOfPassHolders(int newNumber){
    	amountOfPassHolders = newNumber;
    }
    
    /**
     * @return amountOfReservations Amount of reservations made in the car park
     */
    public int getNumberOfReservations(){
    	return amountOfReservations;
    }
    
    /**
     * Change the amount of reservations to be made in the car park.
     * @param newNumber The new amount to set
     */
    public void setNumberOfReservations(int newNumber){
    	amountOfReservations = newNumber;
    }
}


